ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_password_hash;
ALTER TABLE users DROP COLUMN IF EXISTS auth_provider;
ALTER TABLE users DROP COLUMN IF EXISTS google_id;
ALTER TABLE users ALTER COLUMN password_hash SET NOT NULL;
DROP TYPE IF EXISTS auth_provider_type;
